### ISSUE TITLE
Eslint not correctly reformat fragments

### ISSUE THREAD

**Issue by staevs** [tablecheck/tablecheck-react-system#49]
Running `tablecheck-scripts lint --fix` command converts `<Fragment></Fragment>` into `<React.Fragment></Fragment>`.

**Comment by SimeonC** [comment]
Please add a full code fragment including the imports. I can't replicate this.

**Comment by SimeonC** [comment]
I setup a PR that "should" fix the scenario you outlined, but I couldn't replicate the exact case you have here. Please add a new failing test to that branch if the pre-release doesn't fix that.

**Comment by staevs** [comment]
> I setup a PR that "should" fix the scenario you outlined, but I couldn't replicate the exact case you have here. Please add a new failing test to that branch if the pre-release doesn't fix that.

With the canary version I get `AssertionError [ERR_ASSERTION]: Fix objects must not be overlapped in a report` when running `tablecheck-scripts lint --fix` command
